### ISSUE TITLE
Specific GTFS feed yielding invalid charts

### ISSUE THREAD

**Issue by brodyFlannigan** [BlinkTagInc/gtfs-to-chart#6]
# Metadata
- GTFS-to-Chart version: `2.0.0`
- Operating system: Windows 10
- NPM version: `6.14.13`
- GTFS used: [This GTFS feed](https://github.com/BlinkTagInc/gtfs-to-chart/files/6945528/sto-compressed.zip)
- Config: [This config -- download and change extension to .json and edit path to GTFS](https://github.com/BlinkTagInc/gtfs-to-chart/files/6945537/config-STO-20210806-tidy.txt)
- Browser: Chrome

# Problem
When GTFS-to-Chart is run using this specific GTFS feed, the charts generated are invalid. Instead of all the stops being spread out across the chart, they appear to all be stuck against the leftmost side of the chart. No lines appear in the chart. [Example of broken chart -- download and change extension to .html](https://github.com/BlinkTagInc/gtfs-to-chart/files/6945556/11.txt). Note that all charts generated have this issue.
This issue only occurs using the provided GTFS feed, which is the STO GTFS feed run through [GTFSTidy](https://github.com/patrickbr/gtfstidy) with the `-c` flag to create a `calendar.txt` file as the original GTFS only contains `calendar_dates.txt`. Other GTFS feeds work out of the box.
# Expected behaviour
Charts should have stops spaced out across the chart and lines should appear.

Thanks!

**Comment by brendannee** [comment]
Thanks for the detailed report.

Since stop_times.txt doesn't have `shape_dist_traveled`, it was having a hard time placing stops on the chart. I pushed an update that should resolve this, checkout version 2.0.1.

<img width="723" alt="Screen Shot 2021-08-17 at 2 41 15 PM" src="https://user-images.githubusercontent.com/96217/129790003-5995ba65-b612-4305-bf9d-93533d9c1822.png">
